# Site settings
title: "WALLETH - Android Ethereum wallet"
email: ligi@ligi.de
description: "WALLETH - the native Ethereum Android light client wallet"
baseurl: ""
url: "http://walleth.org/"
title_description: "WALLETH is the native Ethereum Android light client wallet,"
#google_analytics: "UA-20365477-4"
github_repository: https://github.com/walleth
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  walleth
instagram_username: 
reddit_username: walleth
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"http://ligi.de\">ligi</a> - theme by <a href=\"https://github.com/jacobtomlinson//carte-noire\">carte noire by Jacob Tomlinson</a>"
footer_right: "source on <a href=\"https://github.com/walleth\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
